[package]
name = "crypto-math-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curve25519-dalek = "3"
rand_core = "0.5"
sha3 = "0.10.5"

[[bin]]
name = "main"
path = "src/main.rs"
